### PR TITLE
Simple support for Access-Control-Allow-Origin

### PR DESCRIPTION
**Pull request by otoolep**
Address https://github.com/rqlite/rqlite/issues/687 in a basic manner.

### CODE REVIEW

**Comment by mikroskeem** [comment]
I believe it'd be useful to set `Access-Control-Allow-Methods: GET, POST` & `Access-Control-Allow-Headers: Content-Type` ([see why Content-Type should be set explicitly](https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_request_header)) because we can send queries using both GET & POST, and `Access-Control-Allow-Credentials: true` if basic authentication is enabled.

In addition you'd need to add support for `OPTIONS` method on any of the endpoints - that's for [preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request). Replying with status 204 & CORS headers is sufficient.

**Comment by otoolep** [comment]
@mikroskeem -- thanks for the pointers. Just to be clear, even if ensure rqlite sets all the right headers such that it "supports CORS", it seems like `Access-Control-Allow-Origin` is the only one that needs to be user-configurable, right? Or perhaps the user might want to also control which methods can be invoked by the "origin"?

**Comment by mikroskeem** [comment]
Being able to configure origin will do just fine for now.

I believe that if anyone wants to configure anything more complex like what you described, they'd go for reverse proxy.

**Comment by patdx** [comment]
I made a little sandbox to test out different variations of CORS here:

- https://github.com/patdx/rqlite-sandbox
- https://patdx.github.io/rqlite-sandbox/rqlite-sandbox.html

It's a standalone HTML file so you can download it and double click it to run locally from your computer too. If both the HTTP GET and HTTP POST actions can work with authentication and without errors then I think that should be reasonable.

> it seems like Access-Control-Allow-Origin is the only one that needs to be user-configurable, right?

I agree this would fit the kinds of light uses I had in mind too.

-----

As far as I can understand the `Access-Control-Allow-Credentials: true` is for using the browser's credential store, kind of similar to how the browser can remember cookies. It seems reasonable to allow it, but I'm not sure if there is a good way to make use of it with rqlite at the moment. I think the server needs to challenge the user for credentials via a [WWW-Authenticate](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate) header but I don't think rqlite does this? It just returns a plain 401 Unauthorized from what I can see.

image

More info: https://www.sjoerdlangkemper.nl/2018/09/12/authorization-header-and-cors/

For credentials provided by setting the `Authorization` header directly in JavaScript, whether or not I set `Access-Control-Allow-Credentials: true`, It was still necessary add Authorization to the Access-Control-Allow-Headers to get it to work.

For **Access-Control-Allow-Methods**, I didn't find this necessary. It seems like GET, HEAD, POST may be allowed by default? https://stackoverflow.com/a/44385327 But based on the documentation it does seem like they would prefer you to set it explicitly.

----

Conclusion:

In my test I ended up needing the following headers to get it to work: https://github.com/patdx/rqlite-sandbox/blob/main/Caddyfile

```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: {{user input here}}
Access-Control-Allow-Headers: authorization, content-type
Access-Control-Allow-Methods: GET, POST
```

Preflight OPTIONS request support is also necessary. In particular for `/db/execute` and `/db/query` but also likely for other URLs.

**Pull request closed without merging**
