### PR TITLE
check level before freshness

### PR DESCRIPTION
**Pull request by wangfenjin**
Change-Id: I6d736ad09eac9f003f087adaa9c1f51691fd5c69

### CODE REVIEW

**Comment by wangfenjin** [comment]
I think re-run the CI would fix the AppVeyor error

**Comment by otoolep** [comment]
Thanks for your contribution, I will take a look. However I'm not sure it's a flaky test. This is the error:
```
\Temp\1\rqlilte-test-663571616 127.0.0.1:1209}
--- FAIL: Test_MultiNodeExecuteQueryFreshness (1.34s)
    store_test.go:808: freshness violating query didn't return an error
=== RUN   Test_StoreLogTruncationMultinode
[store] 2020/03/22 08:13:00 opening store with node ID C:\Users\appveyor\AppData\Local\Temp\1\rqlilte-test-947982207
[store] 2020/03/22 08:13:00 ensuring directory at C:\Users
```
Maybe there is something special about Windows?

**Comment by otoolep** [comment]
I've kicked the build again, but we should dig into the error since it seems related to the area of code you're working in.

**Comment by otoolep** [comment]
Nope, second run, test still fails. Something about Windows?

**Comment by otoolep** [comment]
Thank you for your bug fix, I have merged it to another branch, added more changes, and will soon merge to master.

**Pull request closed without merging**
