### PR TITLE
Fix https redirect http protocol

### PR DESCRIPTION
**Pull request by weenxin**
[Https redirect to http protocol #577](https://github.com/rqlite/rqlite/issues/577)

### CODE REVIEW

**Comment by otoolep** [comment]
While this would probably solve the problem in practice, it does assume that the other node is using HTTP just because this node is running HTTPS. This is not guaranteed to be true.

**Comment by weenxin** [comment]
@otoolep  yes, Absolutely right.

But This will be very varied , When a cluster has three nodes,  node0 use https, node1 use http, and node2 use https.

I think we have  done a  reasonable assumption. All nodes in same cluster should use the same configuration.

What do you think ?

**Comment by otoolep** [comment]
@weenxin -- take a look at https://github.com/rqlite/rqlite/pull/579. I think I prefer that approach. During the join logic the system tries HTTPS is HTTP fails. Can you try this patch, and see if it works for you? I tested it and it works for me.

**Comment by otoolep** [comment]
v5 development is now highly speculative, it may not continue in its current form.

Thanks for the PR however, I appreciate the contribution.

**Pull request closed without merging**
