### PR TITLE
Fix typos and Grammar issues

### PR DESCRIPTION
**Pull request by chermehdi**
This is mainly a boyscout kind of PR, trying to read a little bit of the codebase and fixing grammar and typos.

I also changed a couple of error message capitalization according to: https://github.com/golang/go/wiki/CodeReviewComments#error-strings

### CODE REVIEW

**Comment by otoolep** [comment]
Thank you for your contribution, I appreciate it. There is only two changes I'd prefer were reverted. Once those changes go in, I'm happy to commit.

**Comment by chermehdi** [comment]
@otoolep Could you point out what changes you need reverted?

**Comment by otoolep** [comment]
As per comments above, I don't want those two commas after "In reality you probably". I don't think the sentence reads correctly with them in place.

**Comment by otoolep** [comment]
Actually, I'll merge and make the changes myself -- thanks again for your help.

**Pull request merged**
