### PR TITLE
add server

### PR DESCRIPTION
**Pull request by narg95**
# Description

- Add the `server` package
- Add a `Server` struct to control the life cycle of a rqlite server with methods like `server.Start()` and `server.Stop()` server
- move server bootstrapping from `cmd/rqlited/main.go` to the new `Server` definition
- Introduce a `Config` struct to hold the server configuration settings

Issue #571 

# Questions

I was not able to find where the http server is gracefully shutdown, it looks like missing.

### CODE REVIEW

**Comment by narg95** [comment]
Please take a look to added test and let me know if you find it valuable or if that behavior is already covered by system tests, because currently the race detector is complaining but `server.Start` is not meant to be called concurrently.

**Comment by otoolep** [comment]
Thanks for your work -- this does make sense. I can see what you've got in mind.

I do agree that the `main` layer has got too big, and that this would be one way to refactor. But there may be other ways, I'd need to think about. There may be more than one concept wrapped up in `Server` for example. The config blob is very big, for example -- but that reflects all the composition done by `main` which this PR pushes into a `Server` object.

I'll have to think about this. It's not that it doesn't make sense, but any large change to the codebase in the past was made because *I* could really see it was needed, and it was a step towards where *I* wanted to take the database. At this time time I don't have a strong enough incentive to make such a big change, which I don't feel strongly about, to meet a need that is distinct from rqlite's core goal. Does this make sense?

So I'm happy to leave this open, but unless it makes it also significantly easier to work with the codebase, I'm not going to rush into merging this.

**Comment by otoolep** [comment]
rqlite's core goal == lightweight, distibuted database built on SQLite.
Goal of this PR == make rqlite usable as a package by others.

These are different goals, that's all. And I only have cycles to work on the first goal. They aren't necessarily in conflict, but wrapping a higher-level abstraction around the current code is going to take me weeks to get comfortable with. But you've given me something to think about. :-)

**Comment by otoolep** [comment]
Thanks for this contribution, I'm going to be making very significant changes to main.go now, so it was best to hold off.

**Pull request closed without merging**
