### PR TITLE
Try appveyor

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
Seems like I need to configure a path to gcc or use an alternative for the C code.

https://ci.appveyor.com/project/otoolep/rqlite/build/1.0.0.5

**Comment by lygstate** [comment]
Yes, you need mingw for gcc.

**Comment by otoolep** [comment]
@lygstate -- do you know how to install mingw on appveyor?

**Comment by lygstate** [comment]
Please refer to
https://github.com/servo/servo/blob/master/appveyor.yml#L45

**Comment by otoolep** [comment]
OK, thanks @lygstate.  I tried something really dumb, for kicks. It didn't work, I didn't really expect it to.

The only way I'm going to get this to work is if someone forks rqlite, and generates an `appveyor.yml` file that actually works. I am unable to work on it personally, but would be happy to merge a working PR.

**Comment by otoolep** [comment]
All done via https://github.com/rqlite/rqlite/pull/199

**Pull request closed without merging**
