### PR TITLE
add support for sqlite RETURNING clause

### PR DESCRIPTION
**Pull request by elv-gilles**
This PR adds support for [sqlite RETURNING clause](https://www.sqlite.org/lang_returning.html).

Requests involving the returning clause must include a boolean field before the SQL statement (see `ParseRequest` in `http/request_parser.go`).

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks for your contribution, however this is not the way to solve this. Instead the SQL parser that rqlite uses should be updated to detect when a SQL statement contains `RETURNING` and then rqlite should automatically do the right thing. That is my plan anyway.

The SQL parser is here: https://github.com/rqlite/sql

It would that code that needs support added for detecting `RETURNING`.

**Comment by otoolep** [comment]
Unless I am missing something that will prevent `RETURNING` support being added to the SQL parser, I do not plan to merge this PR.

**Comment by otoolep** [comment]
Thanks again for your contribution. If you'd instead like to add support to the SQL parser Go code, I would be interested in a such a PR. Basically some way that the parser could tell you `RETURNING` was in a given statement, allowing new logic to kick in in rqlite.

**Comment by otoolep** [comment]
I would suggest you propose some of your ideas first though (usually as a GitHub issue), as I  wouldn't like folks to spend a long time coding something, only to find out later that it didn't make sense when created as a PR.

**Comment by elv-gilles** [comment]
OK, no problem: I missed the SQL parser. 

I agree this is a better solution and am looking into the parser.

**Comment by elv-gilles** [comment]
I implemented support in the sql parser (https://github.com/rqlite/sql/pull/9), which unfortunately seems to have an issue (https://github.com/rqlite/sql/issues/10).

For the time being, I'll use what I proposed in this PR (from fork)

**Comment by elv-gilles** [comment]
Notes:
* relates to #1157
* I tried several golang parsers (including `rqlite/sql`) and found [github.com/auxten/postgresql-parser](https://github.com/auxten/postgresql-parser) supporting complex statements **and** the returning clause.

**Pull request closed without merging**
